def class_names():
    class_names = [ 'transformation',
          'prosperity',
          'personal power',
          'bravery',
          'independence',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'renewal, visits from loved ones',
          '',
          '',
          '',
          '',
          '',
          'adventure, youth',
          '',
          'rebirth',
          '',
          '',
          '',
          '',
          '',
          'healing',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'destruction, danger',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'confidence, power',
          '',
          '',
          '',
          'fertility, healing',
          '',
          '',
          '',
          '',
          '',
          'joy, happiness',
          '',
          'travel, clarity',
          '',
          '',
          '',
          '',
          '',
          '',
          'peace, trust',
          '',
          'romance, magic',
          '',
          'flow, intuition',
          '',
          '',
          '',
          '',
          'power, order',
          'persistence, patience',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'adventure, exploration',
          '',
          '',
          '',
          '',
          'beauty, cooperation',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'self-esteem, delusion',
          'letting go of judgement',
          'family, unity',
          '',
          '',
          '',
          'unnecessary journeys',
          '',
          'luck, wealth',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'quarrels with neighbors',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'loyalty, devotion',
          'friendship, affection',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'patience, reliability',
          '',
          '',
          '',
          '',
          'protection, sensitivity',
          '',
          '',
          '',
          'loyalty, obedience',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'sorcery, trickery',
          'cleverness, playfulness',
          '',
          '',
          '',
          '',
          '',
          'agility, curiosity',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'courage, justice',
          '',
          '',
          '',
          'confidence, leadership',
          'courage, ferocity',
          '',
          '',
          'awareness, quick wit',
          '',
          'protection, evolution',
          '',
          '',
          '',
          '',
          '',
          '',
          'motivation, abundance',
          'prosperity, communication',
          '',
          'abundance, achievement',
          'good fortune, clairvoyance',
          '',
          '',
          '',
          'rebirth, metamorphosis, change',
          '',
          '',
          'hope, change',
          '',
          '',
          '',
          'awakening, transformation',
          '',
          '',
          '',
          'vigilance, inspiration',
          'mystic abilities, manifestation',
          '',
          'new beginnings, good fortune',
          '',
          '',
          '',
          'caution, strength',
          '',
          '',
          '',
          'friendship, community',
          '',
          'safety, socialization',
          '',
          '',
          '',
          '',
          '',
          '',
          'strength, unity',
          'boldness, power',
          '',
          '',
          '',
          '',
          '',
          'resilience, respect',
          'faith, balance',
          'cunning, instinct',
          '',
          '',
          '',
          'companionship, joy',
          'overload, deprivation',
          '',
          '',
          '',
          '',
          'friend, family',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'financial security, independence',
          'slow and steady action',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'rebellion, perseverance',
          '',
          '',
          '',
          '',
          '',
          '',
          'tradition, illegility',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'introspection, space-bound',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'community, teamwork',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'cool, timely',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'MAGICAL PRESENCE DETECTED',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'nostalgic, retro',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'death, taxes',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'adrenaline, Mondays',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'partner, destiny',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'harmony, balance, rhythm',
          '',
          '',
          '',
          '',
          'drive, passion',
          '',
          '',
          'overcoming obstacles',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'hijinks, serendipity',
          '',
          '',
          '',
          'heart, circulatory system',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'anger, hostility',
          '',
          '',
          '',
          'strength, Sundays',
          '',
          '',
          '',
          '',
          '',
          'gay, Wednesdays',
          '',
          '',
          '',
          '',
          '',
          'kindness, unity, family',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'guidance, tricksters',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'illumination, Fridays',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'sacrifice, fixation',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'balance, opposition',
          'existentialism, naivete',
          'freedom, overwhelming',
          '',
          '',
          '',
          '',
          '',
          '',
          'kingdoms, worlds',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'damp, Thursdays',
          '',
          '',
          '',
          '',
          '',
          '',
          'a good time',
          '',
          'connection, motherhood',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'composure, obfuscation',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'safety, sleep',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'unification, protection',
          'bad haircut, stagnation',
          '',
          'unexpected outcomes, emotional voids',
          '',
          '',
          '',
          '',
          '',
          '',
          'happiness, elegance',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'pleasure, indulgence',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'bounty, fiber',
          '',
          '',
          '',
          '',
          '',
          '',
          'prosperous future, difficult marriage',
          '',
          '',
          'evolution, revolution',
          '',
          'humility, modesty',
          '',
          '',
          '',
          'delicacies, welcome',
          '',
          '',
          '',
          'fertility, beauty',
          '',
          '',
          '',
          '',
          '',
          'harmony, togetherness',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'relaxation, peace',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'insurrection, self-awareness',
          '',
          '',
          '',
          '',
          'simplicity, joy',
          '',
          'fertility, prosperity',
          'potential, spiritual growth',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          'responsibility, duty']
    return class_names

